server:
  port: 8081
  servlet:
    context-path: /api


spring:
  application:
    name: shipment-service

  #kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shipment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.arielzarate.shipment.interfaces.kafka.dto.OrderPaidEvent
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  #database
  datasource:
    url: jdbc:postgresql://localhost:5432/shipment_management
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


# External clients
externals:
  user-client:
    host: http://localhost:4000
    path: /api/users
    timeout: 5000
  address-client:
    host: http://localhost:4000
    path: /api/address
    timeout: 5000

# Api key
external:
  api-key: idApp1237897key
  device-id: idDevice321567Device


# scheduled
scheduled:
  preparing-to-shipped:
    period: "0 */1 * * * *"
  shipped-to-delivered:
    period: "30 */2 * * * *"



#Monitoring - metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
