server:
  servlet:
    context-path: /api

spring:
  application:
    name: products-service

  #database
  datasource:
    url: jdbc:postgresql://localhost:5432/products_management
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


# Api key
external:
  api-key: idApp1237897key
  device-id: idDevice321567Device

# JWT
jwt:
  secret: sapee2026superSecretKeyForJwt256bits!!


#Monitoring - metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
